# Generated by Django 4.2.11 on 2024-04-28 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('C', 'Cardio'), ('S', 'Strength'), ('M', 'Mobility'), ('R', 'Recovery'), ('W', 'Warmup'), ('O', 'Other')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='SessionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Session Date')),
                ('hrv', models.IntegerField()),
                ('program_info', models.CharField(max_length=150)),
                ('rpe', models.IntegerField()),
                ('notes', models.TextField()),
                ('exercise', models.ManyToManyField(to='kb_fit.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kb_fit.exercise')),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='types',
            field=models.ManyToManyField(to='kb_fit.exercisetype'),
        ),
    ]
