# Generated by Django 4.2.11 on 2024-04-28 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb_fit', '0002_sessionentry_warmup_alter_sessionentry_exercise'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='reps',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exercise',
            name='sets',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exercise',
            name='time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sessionentry',
            name='hrv',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sessionentry',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sessionentry',
            name='program_info',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='sessionentry',
            name='rpe',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
