# Generated by Django 4.2.11 on 2024-04-30 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb_fit', '0003_exercise_reps_exercise_sets_exercise_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='time',
            field=models.CharField(blank=True, null=True),
        ),
    ]
