# Generated by Django 4.2.11 on 2024-04-30 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb_fit', '0004_alter_exercise_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
