# Generated by Django 4.2.11 on 2024-05-02 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kb_fit', '0007_exercise_user_sessionentry_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reps', models.IntegerField(blank=True, default=0, null=True)),
                ('sets', models.IntegerField(blank=True, default=0, null=True)),
                ('time', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SessionWarmup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reps', models.IntegerField(blank=True, default=0, null=True)),
                ('sets', models.IntegerField(blank=True, default=0, null=True)),
                ('time', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Warmup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('types', models.ManyToManyField(to='kb_fit.exercisetype')),
            ],
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='reps',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='sets',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='time',
        ),
        migrations.RemoveField(
            model_name='sessionentry',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='sessionentry',
            name='warmup',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
        migrations.AddField(
            model_name='sessionwarmup',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kb_fit.sessionentry'),
        ),
        migrations.AddField(
            model_name='sessionwarmup',
            name='warmup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kb_fit.warmup'),
        ),
        migrations.AddField(
            model_name='sessionexercise',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kb_fit.exercise'),
        ),
        migrations.AddField(
            model_name='sessionexercise',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kb_fit.sessionentry'),
        ),
        migrations.AddField(
            model_name='sessionentry',
            name='exercises',
            field=models.ManyToManyField(related_name='exercise_sessions', through='kb_fit.SessionExercise', to='kb_fit.exercise'),
        ),
        migrations.AddField(
            model_name='sessionentry',
            name='warmups',
            field=models.ManyToManyField(related_name='warmup_sessions', through='kb_fit.SessionWarmup', to='kb_fit.warmup'),
        ),
    ]
