# Generated by Django 4.2.11 on 2024-05-02 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kb_fit', '0008_sessionexercise_sessionwarmup_warmup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionentry',
            name='exercises',
            field=models.ManyToManyField(blank=True, null=True, related_name='exercise_sessions', through='kb_fit.SessionExercise', to='kb_fit.exercise'),
        ),
        migrations.AlterField(
            model_name='sessionentry',
            name='warmups',
            field=models.ManyToManyField(blank=True, null=True, related_name='warmup_sessions', through='kb_fit.SessionWarmup', to='kb_fit.warmup'),
        ),
        migrations.AlterField(
            model_name='sessionexercise',
            name='exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kb_fit.exercise'),
        ),
        migrations.AlterField(
            model_name='sessionwarmup',
            name='warmup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kb_fit.warmup'),
        ),
    ]
