# Generated by Django 4.2.11 on 2024-05-03 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb_fit', '0009_alter_sessionentry_exercises_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionentry',
            name='exercises',
            field=models.ManyToManyField(related_name='exercise_sessions', through='kb_fit.SessionExercise', to='kb_fit.exercise'),
        ),
        migrations.AlterField(
            model_name='sessionentry',
            name='warmups',
            field=models.ManyToManyField(related_name='warmup_sessions', through='kb_fit.SessionWarmup', to='kb_fit.warmup'),
        ),
    ]
